package com.muzima.api.model;

import java.util.List;

/**
 * TODO: Write brief description about the class here.
 */
public class CohortData extends OpenmrsSearchable {

    private boolean dynamic;

    private Cohort cohort;

    private List<Member> members;

    private List<Patient> patients;

    /**
     * Get the flag whether the cohort is a dynamic or static one. Dynamic cohort data is generated by the reporting framework,
     * static cohort is generated by the cohort builder or programmatically inserted into the cohort table.
     *
     * @return true when the cohort is a dynamic or false when the cohort is a static cohort.
     */
    public boolean isDynamic() {
        return dynamic;
    }

    /**
     * Set the flag whether the cohort data is a dynamic or static one.
     *
     * @param dynamic the flag.
     */
    public void setDynamic(final boolean dynamic) {
        this.dynamic = dynamic;
    }

    /**
     * Get the cohort for this cohort data object.
     *
     * @return the cohort for this cohort data object.
     */
    public Cohort getCohort() {
        return cohort;
    }

    /**
     * Set the cohort for this cohort data object.
     *
     * @param cohort the cohort for this cohort data object.
     */
    public void setCohort(final Cohort cohort) {
        this.cohort = cohort;
    }

    /**
     * Get the members for this cohort data object.
     *
     * @return the members for this cohort data object.
     */
    public List<Member> getMembers() {
        return members;
    }

    /**
     * Set the members for this cohort data object.
     *
     * @param members the members for this cohort data object.
     */
    public void setMembers(final List<Member> members) {
        this.members = members;
    }

    /**
     * Get the patients for this cohort data object.
     *
     * @return the patients for this cohort data object.
     */
    public List<Patient> getPatients() {
        return patients;
    }

    /**
     * Set the patients for this cohort data object.
     *
     * @param patients the patients for this cohort data object.
     */
    public void setPatients(final List<Patient> patients) {
        this.patients = patients;
    }
}
